name: base
channels:
  - conda-forge
dependencies:
  - git=2.47.0 
  - ipykernel>=6.29.5
  - jedi-language-server>=0.41.4
  - jupyter-resource-usage>=1.1.0
  - jupyterlab-git>=0.50.1
  - jupyterlab-lsp>=5.1.0
  - jupyterlab=4.2.5
  - notebook=7.2.2